# Need to use "trusty" for Java 1.8
# ref: https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/
sudo: required
dist: trusty

language: python

python:
  - "2.7"

# cache pip and npm package installations
cache:
  pip: true
  directories:
    - node_modules

# limit the depth of the commits we clone
git:
  depth: 5

addons:
  firefox: "50.1.0"
  browserstack:
    secure: "JQ9ZK07B98zZ67dGChFLA+1oqoB+xhh6iL2NFhiV6mYetFC8ZT3fc7xtAJyiloIn0qqi4pyByAz+S/DocxAYd+M0EqwEvqM6BT9QyL5N4F7gFdodAmNuVq4jd/WL2md/s238eUVhhxWhKFgIQCqI/4JgnubdRxWntSGo2k/vYqLUlaf6Qg6Of8eoKKJpfu6juP/On8mnQwJSZgSsODbf7BmHlXZrtleciPpdFduo+AwoxHiW34+c8ZIKZ8niGGEe1zQsCAeoR75a5tjtBBL3HMA8yMY9M+e7+jrLq2oY5mUBNTLnP0BrLRokIE7LNklPCykw61/jOzYZG8g43X8v+NDkwjSqJFwZOZVq5Cjl/nkvCk4OKVT0EDGlEY+i7bHwpQTYR5egS93E7RgWyHnUAmR2M9iMdJ7FYMSASlE51Vc9OfcPJ3Ag9bkfyjOs/oJ019+UmCD+CJV2ulzCbL4zm0XkzA+NT2ytNETug0CV5OvNXtKimJZpA8BeeEnOUpaNlP3lC8/LohH+SjVjMnPGKMczqVEADiLUaFXQF3rrw8xuWsjmByayBIWpVzSMzO/BBrYE56MQbdkIjrnLeagYln/UdZtln5Dw3co1MZ4yM/fOwf6LotL/hyBde1IuaGuXhPLIkUCO7OaiSjXncWpR5ZwqupsMbfpjAas1csvTZ14="
    secure: "Y3tUJgFQNFDQYkxDzoaofIEAb40uJUvN7fOx4bvjEJRVL958mvGD0fexOE9JYyrztc6RXHyWfmigxZiBWnRFdmuXES5ao8WuhXbNThqQhgHJnbZM0EkOXJ5T72M7xWsLJYJ0o2cIsYR32dKUDVM1AofLIA5MYA0PvAUIbogcyQMzeB+iowIGDxAFnSCt5t17NQEQTSILBdF8RO7grvuXrNtcJP6USoj9sRrz9VHMjYHmbDkUrRWUOTPluvH6E/4xWG3NtPfxpMsxxmKn44utVO+pJ91eXB52itmPI28S0BGbjYY/O7+/czqUKEw5PjE0PYtKN6dsQ3S32ul/i8xo8PV6rCuauR91V6VcYnJtDideP/5/PPqSyCTLPfwnKa/Krr6AfWbsFuJdBQUxZNL8nSMbWYn9Unm7SjANGdb26r1ju9WdMJddwOdX4+IcdVjVmmMVBkSoh6GWO4yJ/+plIovZ5o2fCkZwEuHBu9LuoNHV4QPAqVy7/aDzpfsJOzpM8p+M1Hp/U/W4nholY5t9YHqbaXRb2qTTFDIfrTG6IZYvIoFWDd2nYzOYuPOqHdffm5Eq7/lSN82alCkF4R4eQNnClNTzvD5C6aZrUT/n6iimrNYH/mCUjm1fZY6ERewdrf/YJKrjVGBvUSIGeyQYGggnR8uTK+rbd6/wl9oKA3w="
    forcelocal: true
    only: localhost,5000,0
    #proxyHost: "http://localhost"
    #proxyPort: "5000"

env:
  global:
    - ISSUES_REPO_URI=webcompat/webcompat-tests/issues
    - FAKE_ID=e80a666fbf1fa9ea18db
    - FAKE_SECRET=688c4546f09624f8c44773b22268064dfca19a59
    # grab latest 4.x release, which is LTS for now
    - TRAVIS_NODE_VERSION="4"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - travis_retry npm install -g grunt-cli
  - travis_retry npm install
  - travis_retry npm run pip
  - travis_retry npm run config
  - which firefox
  - java -version
  - firefox --version
  # lint python
  - pep8 --ignore=E402 webcompat/ tests/ config/secrets.py.example
  - npm run module
  - python run.py -t &

before_script:
  - "sleep 2"
  # lint JS in default eslint task
  - npm run lint
  - npm run build

# now run the tests!
# if this is a pull request from a fork, TRAVIS_SECURE_ENV_VARS will be false, so
# just run the non-auth tests. otherwise, run everything.
script:
  - nosetests
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "false" ] ; then node_modules/.bin/intern-runner BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY config=tests/browserstack_remote BROWSERSTACK_USERNAME="$BROWSERSTACK_USERNAME" BROWSERSTACK_ACCESS_KEY="$BROWSERSTACK_ACCESS_KEY" reporters=Console functionalSuites=tests/functional-nonauth ; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] ; then node_modules/.bin/intern-runner config=tests/intern reporters=Console user="$USER" pw="$PW" ; fi
